version: "2"
checks:
  argument-count:
    config:
      threshold: 8
  complex-logic:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 12
  method-count:
    config:
      threshold: 40
  method-lines:
    config:
      threshold: 32
  nested-control-flow:
    config:
      threshold: 8
  return-statements:
    config:
      threshold: 8
  similar-code:
    enabled: false
  identical-code:
    enabled: false
languages:
  Python: true
exclude_paths:
  - examples/*
  - amqpstorm/tests/*
  - amqpstorm/management/*
