#!/bin/bash
set -eu

SSL_DIR=/etc/rabbitmq/ssl
CURVE=secp384r1

mkdir -p "$SSL_DIR"/certs "$SSL_DIR"/client "$SSL_DIR"/private "$SSL_DIR"/server

echo 01 > "$SSL_DIR/serial"
: > "$SSL_DIR/index.txt"

cd "$SSL_DIR"

openssl req -x509 -config openssl.cnf -newkey ec -pkeyopt ec_paramgen_curve:"$CURVE" -nodes -days 365 -subj /CN=rmq.eandersson.net/ -out ca_certificate.pem -outform PEM
openssl x509 -in ca_certificate.pem -out ca_certificate.cer -outform DER

openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:"$CURVE" -out server/private_key.pem
openssl req -new -key server/private_key.pem -subj /CN=rmq.eandersson.net/O=server/ -out server/req.pem -outform PEM
openssl ca -config openssl.cnf -in server/req.pem -out server/server_certificate.pem -notext -batch -extensions server_ca_extensions

openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:"$CURVE" -out client/private_key.pem
openssl req -new -key client/private_key.pem -subj /CN=rmq.eandersson.net/O=client/ -out client/req.pem -outform PEM
openssl ca -config openssl.cnf -in client/req.pem -out client/client_certificate.pem -notext -batch -extensions client_ca_extensions
